name: IsolatedAKSDeveloperEnvironment
summary: Terraform example for a Developer Sandbox Environment
description: Deploys an environment using Terraform containing AKS, CosmosDB and Event Hub resources.
runner: Terraform
templatePath: main.tf
parameters: 
- id: "region"
  name: "region"
  type: "string"
  default: "southcentralus"
- id: "node_sku"
  name: "node_sku"
  type: "string"
  default: "Standard_D4ads_v5"
  allowed:
    - "Standard_B4s_v2"
    - "Standard_B4ms"
    - "Standard_D4ls_v5"
- id: "node_count"
  name: "node_count"
  type: "number"
  default: 1
- id: "github_repository"
  name: "github_repository"
  default: "https://github.com/briandenicola/deployment-environments"
  type: "string"
- id: "branch_name"
  name: "branch_name"
  default: "main"
  type: "string"
- id: "deploy_cosmos_db"
  name: "deploy_cosmos_db"
  default: "false"
  type: "string"
- id: "deploy_event_hub"
  name: "deploy_event_hub"
  default: "false"
  type: "string"